# Extract profiles generated by U_profiles_extract.py and plot them using matplotlib
# -*- coding: utf-8 -*-
# Run using `python U_profiles_plot.py`

import csv
import matplotlib.pyplot as plt
import numpy as np

def U_extract(file):
    with open(file) as f:
        #row_count = sum(1 for row in f)
        x = []
        u = []
        v = []
        w = []
        reader = csv.DictReader(f, delimiter=',')
        for row in reader:
            x.append(float(row['arc_length']))
            u.append(float(row['U:0']))  # Access by column header instead of column number
            v.append(float(row['U:1']))
            w.append(float(row['U:2']))
            
        x = np.array(x)
        u = np.array(u)
        #v = np.array(v)
        #w = np.array(w)
        
        x = x*100
        #Umag = np.sqrt((u**2)+(v**2)+(w**2))*1000
        #print(Umag.shape)
        U_final = np.array((x, u*100))#Umag
        
        return U_final
    
cases = np.array(["deg0", "deg45", "deg90", "deg135", "deg180"])
files = np.array(['Uloc_1.csv', 'Uloc_2.csv', 'Uloc_3.csv'])
arr = np.arange(0,len(cases),1)
#Uloc1 = np.empty((2,1001))
#Uloc1 = U_extract('n80/Uloc1.csv')

plt.rcParams.update({'font.size': 10})
fig, axs = plt.subplots(1, 3)
fig.set_figheight(4) #height and width in inches. Width of A4 sheet is 8.27 in
fig.set_figwidth(7)
fig.set_dpi(300)

locs = ['Uloc_1', 'Uloc_2', 'Uloc_3']

#for i in range(len(files)):
#    col = i%3
#    dir = '../'+cases[i]+'/postProcessing/'
#    axs[col].set_title(locs[i], fontsize=10)

#    for j in arr:
#        data = U_extract(dir+files[i])
#        axs[col].plot(data[1], data[0], linewidth=1, label=f'{cases[j]}')
for i in range(len(files)):
    col = i % 3
    axs[col].set_title(locs[i], fontsize=10)

    for j in arr:
        dir = '../' + cases[j] + '/postProcessing/'
        file_path = dir + files[i]
        print(f"Loading: {file_path}")
        data = U_extract(dir + files[i])
        print(f"First 5 u values for {cases[j]}: {data[1][:5]}")
        axs[col].plot(data[1], data[0], linewidth=1, label=f'{cases[j]}')

for ax in axs.flat:
    ax.set(xlabel='u (cm/s)', ylabel='z (cm)')
    ax.set_xticks([0,5,10])
    
for ax in axs.flat:
    ax.label_outer()
    
handles, labels = axs[0].get_legend_handles_labels()
print(handles,labels)
#fig.legend(handles, labels, loc='center left')
# Place the legend to the right of the figure
fig.legend(
    handles, labels,
    loc='center right',
    #bbox_to_anchor=(1.02, 0.5),  # adjust this to move legend further right/left
    #borderaxespad=0,
    title='Locations'
)

# Make room for the legend on the right
plt.subplots_adjust(right=0.82)  # Adjust as needed
plt.savefig('../U_profiles.pdf')